title: Keluarga Cactus - Jual kaktus dan sukulen Indonesia
author: Kim
email: admin@keluargacactus.com
description: > # this means to ignore newlines until "baseurl:"
 Toko Kaktus Online yang menyediakan berbagai macam tanaman hias kaktus & sukulen dengan kualitas terbaik.

twitter_username: jekyllrb
github_username:  jekyll
instagram_username: keluargacactus
facebook_username: keluargacactus
whatsapp_api: 6285256404594
whatsapp_readable: 085 256 404 594

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
